crabbly/Print.js

src/js/browser.js

Attempt for fix #30 and https://github.com/facebookincubator/create-react-app/issues/1838
UglifyJS does not understand this notation. It's also not consistent within file so es5 notation should be better for this.

Change es6 shorthand notation to es5 notation

---

src/js/print.js

Hi, I add this function to enable user to customize the column name while printing json formatter. It will not break the original usage but will accept a new way of json config:
printJS({printable: someJSONdata, properties: [
**{'displayName':'Myname', 'field':'name'},
{'displayName':'Myemail', 'field':'email'}, 
{'displayName':'Myphone', 'field':'phone'}**
], type: 'json'})

enable customizing filed display name while printing json

---

README.md

[https://standardjs.com/#the-rules](https://standardjs.com/#the-rules)
> 2 spaces – for indentation

Remove guideline that incompatible with Standard Style

---

webpack.mix.js

In https://github.com/crabbly/Print.js/pull/103 I modified the entrypoint to be the minified version.  But, when trying to import the new published version in my project, I got an error.
This updates the webpack config to generate a UMD that can be imported by CommonJS, AMD or as a property on root.
I checked by doing a sym link in `node_modules/` to the folder with this branch and this seems to fix it. I also checked including the minified version and it exports it as a global window object correctly.
Sorry for the issue, and thanks for being an active maintainer!

Output as UMD

---

src/js/init.js

If provided, fallbackPrintable is used for the URL in browsers that require opening PDFs in a new tab.

Add optional fallbackPrintable parameter

---

src/js/init.js
src/js/json.js

There were 2 issues which made me update the json printable type:
1. In case of having a large dataset (let's say more than one page), the table column needs to be repeated at the beginning of each page. This was missing.
2. Since the printable is defined as a combination of many `<div>` elements, in case of having a cell in the middle of page with larger contents than the expected size, the cell increases the width rather than increasing the height. This made me change the `<div>` elements to `<table>`. In this branch, this issue resolved and in such cases, the cell will increase the height and not the width.

Enhancing the json printable type

---

src/js/init.js
src/js/json.js

By default all tableHeaders in JSON printableType will be repeated in each page but in case the user doesn't need this, the repeatTableHeader attribute can be set to false.

Adding repeatTableHeader attribute for JSON printable

---

src/js/init.js
src/js/print.js
test.html

Since there wasn't any way to use `@media print` and/or any custom css specific for printing, i tried my hand at adding that function.
Pass a string to `css` parameter and that's it.
Thanks for the library, but it really needs that =)

Add custom css support (including media print)

---

src/js/html.js
src/js/init.js
src/js/print.js
test.html

I added the option to add external css files urls as an array parameter externalCss
For example `externalCss: ['https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css']`
Also the boolean parameter scanStyles for toggling the scanning and inlining of the elements css.
I think we should keep all the options available for any use cases, for example I like the scanning of the css but would like to add `@media print` for page margin or some small stuff, which I would like to just put as a small string instead of it's own file or whatever. Also I think it's more useful for frontend framework users (or I'm too dumb to find how to, so I'll use it simply like that :))

Add array of external css parameter, and option to disable css scanning

---

src/js/functions.js
src/js/init.js
src/js/pdf.js
src/js/print.js
test.html

This option enables print "completion" notification, when possible.
Note that these implementation is somehow weak as we don't currently
have a way to know whether the user printed the document or not, so
the use of "print completion notification" is misleading.
Another issue to highlight is that this implementation depends upon
window's mouseover event, this means that, while the print dialog
is open, the window does not have the focus and thus, the mouseover
event will not be fired. However, this is not the case for Firefox,
because the print dialog does not removes the focus from window.
Last, the implementation is inspired in StackOverflow's thread [how
to detech window.print() finish](https://stackoverflow.com/q/18325025)
and the two responses https://stackoverflow.com/a/35430328 and …

Add onPrintDialogClose callback option

---

src/js/pdf.js

Currently, object URLs created on a file:// origin are not handled correctly, resulting in an additional origin prefix and rendering the object URL invalid. This PR treats URLs starting with either http or blob as complete.

improve object url handling

---

package.json

When I use `npm link` to include a local version of `print-js`, webpack fails with the error "Can't resolve 'print-js'".  This is because `npm run dev` creates `dist/print.min.js` but the `package.json` advertises `dist/print.js` as the entry point.
Fixing that build error by setting package.json's `main` field to the file that webpack builds.

Fix "Can't resolve 'print-js'" build error

---

src/js/init.js
src/js/print.js

Also clean up the modal when an error is passed to `onError`.
I am not trying to catch all errors.  That would be a big project!  But hopefully catching some errors is an imprevement and additional error catching can be added incrementally.
Does it seem right to call `onLoadingEnd` when an error happened?
Test cases:

Add new onError callback param that receives errors from async code.

---

src/js/print.js

This bug caused the image to not print unless it was already loaded when `loadIframeImage()` was first called.  Otherwise any subsequent calls to `loadIframeImage()` would create a new promise and then resolve that new promise -- instead of resolving the original promise that was being waited on by the `Promise.all()` returned by `loadIframeImages()`.
I tested before and after my change on Linux Chrome, Linux Firefox, Windows 10 Edge, and Windows 10 IE11.  Interestingly, it worked pretty reliably on IE11 and Firefox *before* the fix.  It usually failed on Chrome and Edge before the fix.

Fix bug that stopped images from printing.

---

src/js/init.js
test.html

To work similarly to the onPrintDialogClose callback, but for when the pdf is opened in a new tab for Firefox/Edge/IE

Added onPdfOpen callback option

---

webpack.config.js

Tell Webpack to that this is a library.
This fixes the following error when calling `printJS()` after importing it via `import printJS from 'print-js'`:
> TypeError: __WEBPACK_IMPORTED_MODULE_2_print_js___default(...) is not a function

Fix undefined default export

---

README.md
index.d.ts
src/index.js
webpack.config.js

Expose `printJS` function on the window object (if window exists) (see `/src/index.js`)
Build package via Webpack as a UMD library and purposefully rename
`print` to avoid conflicts.
Update Typescript typings file to reflect this.
Good resources:
http://siawyoung.com/coding/javascript/exporting-es6-modules-as-single-scripts-with-webpack.html
https://webpack.js.org/guides/author-libraries/
https://stackoverflow.com/questions/40294870/module-exports-vs-export-default-in-node-js-and-es6/40295288#40295288

Properly support `window.printJS` and module `print`

---

src/js/browser.js
test/unit/browser.spec.js

The `window.chrome` object has no `webstore` property defined.
Closes #256

Fix chrome detection

---

src/js/init.js
test/manual/index.html

In case of browser incompatible (firefox, edge, IE), possibility to do something and open or not the pdf in new tab. 
For example, If onBrowserIncompatible is set, we can display a message like "your browser is incompatible with this feature" and don't open a new tab.

case browser incompatible

---

src/js/pdf.js

This will let the user omit the protocol, e.g.: "//example.com/my.pdf" for "params.printable", and the browser would automatically add the same protocol (http or https) of current url.
https://tools.ietf.org/html/rfc3986#section-4.2

Allow use of relative references for pdf

---

src/js/print.js

This is an alternative to #409
Simply ensure `images` is an array before passing to `loadIframeImages`, so it has access to array functions like `map`.

Fix `images.map is not a function` error

---

src/js/pdf.js

Added XmlHttpRequest error event handler.
On remote print errors such as could not find the url. PrintJS does not handle the error

Remote print errors handling

---

src/js/functions.js

Hello! I found a problem related to targetStyles in IE. A method getComputedStyle returns an object CSSStyleDeclaration. And in all modern browsers a method `Object.keys(styles)` from this object returns an array of keys like ['0', '1', etc]. But in IE11 `Object.keys(styles)` returns an empty array.
Linked to this issue - https://github.com/crabbly/Print.js/issues/182

fix an IE bug related to Object.keys(styles) that returns an empty array

---

src/js/image.js
src/js/init.js
src/js/print.js

Add support for printing PDF in Firefox and fix printing of an image with a non-fully-qualified in Firefox. Fixes #431.

Firefox PDF support and image printing fix

---

src/js/init.js

The issue is that iframes have a default border of 2px, so when printing it's adding a 4x4px at the bottom of the page that in pages using 100vh is an issue because it adds scroll.
iframes default styles:
After printing, at the bottom of the page:
After fix:

fix: override default iframe border so it's really hidden

---

src/js/functions.js

@crabbly Hi again! :) I noticed that I always have wrong property in my styles... Seems to be missed property name. Here it is a new PR from me :)  It's just one small change! Or is it better to remove this part : `params.font_size + ' !important;'` since it is deprecated..

add missed font-size property

---

src/index.d.ts
src/js/pdf.js

Currently the `onError` callback only has the `req.statusText` field,
as param.
Would be useful to have the `XMLHttpRequest` object instance along
with the `req.statusText`, so we are able to consume all the details
from the request, the response (ArrayBuffer) for instance.
When available the `XMLHttpRequest` instance used in the request
is sent as second param for the `onError` callback.
Consider the following request to hypothetical site "https://get-a-pdf.com",
where the server responds with a JSON when an error occurs.
We want to consume the JSON in order to print the message to our users.
```ts
printJS({ 
printable: 'https://get-a-pdf.com',
type: 'pdf',
onError: function(error, xmlHttpRequest) {
// as the `XMLHttpRequest.response` is an instance of
// `ArrayBuffer` we decode the …
```

Feature | Use the XMLHttpRequest instance as second param for `onError` callback

---

src/js/html.js

This feature adds ability for usage like that:
`printJS({
printable: frame.contentDocument.body,
type: 'html',
});`

 Printable can be exact element in html

---

src/js/print.js

In my project, when the html type is printed, the external font is not displayed. I put' iframeelement. contentwindow.print ()' in the setTimeout.

'iframeElement.contentWindow.print()' is placed in the setTimeout.

---

src/js/pdf.js

[**_privt-js version:1.6.0_**](https://www.npmjs.com/package/print-js/v/1.6.0)
```js
//pdf base64 value start with data:application/pdf;base64,
const pdfBase64 = `data:application/pdf;base64,xxxxxxxxx`;
printJS({
printable: pdfBase64,
base64: true,
})
```
The above code causes the error **Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.**
Beacuse **atob** function can‘t transfer the symbol(**,**)
So we should remove this symbol.
----------------🎈🎈🎈-----------------
The following file is a pdf base64 string start with `data:application/pdf;base64,`
[base64WithHeader.txt](https://github.com/crabbly/Print.js/files/9496811/base64WithHeader.txt)

Fix Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
